package com.rosterforge.wh40k.domain.model

enum class Allegiance { IMPERIUM, CHAOS, XENOS, UNALIGNED }

enum class BattlefieldRole {
    EPIC_HERO,
    CHARACTER,
    BATTLELINE,
    INFANTRY,
    MOUNTED,
    VEHICLE,
    MONSTER,
    FLY,
    DEDICATED_TRANSPORT,
    ALLIED_UNITS,
    FORTIFICATION,
    OTHER,
}

enum class WeaponType { RANGED, MELEE }

enum class GamePhase { ANY, COMMAND, MOVEMENT, SHOOTING, CHARGE, FIGHT, MORALE }

enum class StratagemType {
    BATTLE_TACTIC,
    STRATEGIC_PLOY,
    EPIC_DEED,
    WARGEAR,
    STRATEGIC,
    REQUISITION,
}

enum class AbilityType { CORE, FACTION, DETACHMENT, UNIT, DAMAGED, AURA }

enum class ModelScope { PER_MODEL, PER_UNIT, FIXED_NUMBER }

enum class Severity { ERROR, WARNING, INFO }

enum class ValidationCode {
    POINTS_EXCEEDED,
    NAMED_CHARACTER_DUPLICATE,
    UNIT_LIMIT_EXCEEDED,
    LEADER_KEYWORD_MISMATCH,
    LEADER_SELF_ATTACHMENT,
    LEADER_ALREADY_ATTACHED_ELSEWHERE,
    BODYGUARD_HAS_MULTIPLE_LEADERS,
    LEADER_WITHOUT_BODYGUARD,
    ENHANCEMENT_INELIGIBLE,
    ENHANCEMENT_DUPLICATE,
    ENHANCEMENT_WRONG_DETACHMENT,
    ENHANCEMENT_LIMIT_EXCEEDED,
    WARGEAR_EXCEEDS_MAX_SELECTIONS,
    WARGEAR_BELOW_MIN_SELECTIONS,
    WARGEAR_PER_MODEL_EXCEEDS_COUNT,
    MUTUALLY_EXCLUSIVE_WARGEAR,
    FACTION_KEYWORD_MISMATCH,
    DETACHMENT_NOT_IN_FACTION,
    MODEL_COUNT_BELOW_MINIMUM,
    MODEL_COUNT_ABOVE_MAXIMUM,
    BATTLELINE_MINIMUM,
}
